version: '3.8'

services:
  # MySQL database for frontend development
  frontend_db:
    image: mysql:8.0
    container_name: shop_management_frontend_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shop_management_frontend
      MYSQL_USER: frontend_user
      MYSQL_PASSWORD: frontend_password
    ports:
      - "3307:3306"  # Using port 3307 to avoid conflicts with the main database
    volumes:
      - frontend_mysql_data:/var/lib/mysql
      - ./frontend-db-init:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  
  # JSON Server for mock API (optional)
  json_server:
    image: node:16-alpine
    container_name: shop_management_json_server
    working_dir: /app
    volumes:
      - ./frontend-mock-api:/app
    ports:
      - "3010:3000"  # JSON Server will run on port 3010
    command: >
      sh -c "npm install -g json-server && 
             json-server --watch db.json --host 0.0.0.0 --routes routes.json"
    depends_on:
      - frontend_db

volumes:
  frontend_mysql_data:
